# This is a basic workflow to help you get started with Actions

name: Windows Build CI

# Controls when the workflow will run
on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    permissions:
      contents: write
      actions: write
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@main
      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.2.5
      # Runs a set of commands using the runners shell
      - name: script run line haha
        run: |
          haxelib setup "%HAXELIB_ROOT%"
          haxelib install lime 7.9.0
          haxelib install openfl 9.1.0
          haxelib install flixel 4.11.0
          haxelib run lime setup flixel
          haxelib run lime setup
          haxelib install flixel-tools 1.5.1
          haxelib install flixel-ui 2.4.0
          haxelib remove flixel-ui
          haxelib install flixel-ui 2.4.0
          haxelib install flixel-addons 2.11.0
          haxelib remove flixel-addons
          haxelib install flixel-addons 2.11.0
          haxelib git hscript-improved https://github.com/CodenameCrew/hscript-improved.git
          haxelib git polymod https://github.com/larsiusprime/polymod.git branch 38cfe17ba234c58eab7e065021ec44ea8ce1e895
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
          haxelib git extension-webm https://github.com/luckydog7/extension-webm.git
          haxelib run lime rebuild extension-webm windows
          haxelib git linc_luajit https://github.com/superpowers04/linc_luajit.git
          haxelib git hxvm-luajit https://github.com/nebulazorua/hxvm-luajit.git
          haxelib install actuate
          haxelib list
          haxelib run lime build windows
          
      - uses: actions/upload-artifact@main
        with:
          name: Windows Build
          path: export/release/windows/bin
